const state={recipes:[],filtered:[],visible:30,query:"",category:"",diet:"",maxIngredients:"",sort:"relevance",saved:new Set(JSON.parse(localStorage.getItem("feastly-saved")||"[]")),shopping:JSON.parse(localStorage.getItem("feastly-shopping")||"{}"),planner:JSON.parse(localStorage.getItem("feastly-planner")||"{}"),servings:2,cookSteps:[],cookIndex:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icons={main:"🍽️","Desserts":"🍰","Side Dish":"🥔","Salad":"🥗","Breakfast and Brunch":"🥞","Bread":"🍞","Drinks":"🥤"};
const diets={vegan:["meat","chicken","beef","pork","fish","egg","milk","cheese","butter","cream","yogurt","honey"],vegetarian:["chicken","beef","pork","fish","meat"],"dairy-free":["milk","cheese","butter","cream","yogurt"],"gluten-free":["wheat","flour","bread","pasta","barley","rye"],"nut-free":["peanut","almond","walnut","cashew","pecan","hazelnut"]};
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function prettyCategory(s){return s==="main"?"Main dishes":s}
function imageUrl(title){const q=encodeURIComponent(title.replace(/[^a-zA-Z0-9 ]/g,"")+" food");return `https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${q}&gsrnamespace=6&gsrlimit=1&prop=imageinfo&iiprop=url|mime&iiurlwidth=900&format=json&origin=*`}
const imageCache=new Map();
async function findImage(title){if(imageCache.has(title))return imageCache.get(title);try{const r=await fetch(imageUrl(title));const d=await r.json();const p=Object.values(d.query?.pages||{})[0];const i=p?.imageinfo?.[0];if(i?.mime?.startsWith("image/")){const u=i.thumburl||i.url;imageCache.set(title,u);return u}}catch(e){}imageCache.set(title,"");return ""}
function card(r){const saved=state.saved.has(r.slug);return `<article class="recipe-card" data-slug="${encodeURIComponent(r.slug)}"><div class="recipe-image" data-image="${encodeURIComponent(r.title)}"><div class="image-fallback">${icons[r.category]||"🍴"}</div><button class="heart ${saved?"saved":""}" data-save="${encodeURIComponent(r.slug)}" aria-label="${saved?"Remove from saved":"Save recipe"}">${saved?"♥":"♡"}</button></div><div class="recipe-content"><div class="recipe-cat">${escapeHtml(prettyCategory(r.category))}</div><div class="recipe-title">${escapeHtml(r.title)}</div><div class="recipe-meta"><span>${r.ingredients.length} ingredients</span><span>Open →</span></div></div></article>`}
function renderGrid(el,list){el.innerHTML=list.map(card).join("");$$(`${el.id?"#"+el.id+" ":""}.recipe-card`).forEach(c=>c.onclick=e=>{if(e.target.closest(".heart"))return;openRecipe(decodeURIComponent(c.dataset.slug))});$$(`${el.id?"#"+el.id+" ":""}[data-save]`).forEach(b=>b.onclick=e=>{e.stopPropagation();toggleSave(decodeURIComponent(b.dataset.save))});$$(`${el.id?"#"+el.id+" ":""}[data-image]`).forEach(async box=>{const title=decodeURIComponent(box.dataset.image),src=await findImage(title);if(src)box.querySelector(".image-fallback").outerHTML=`<img loading="lazy" alt="${escapeHtml(title)}" src="${src}" onerror="this.remove()">`})}
function matchesDiet(r,d){if(!d)return true;const text=(r.title+" "+r.ingredients.join(" ")).toLowerCase();return !(diets[d]||[]).some(x=>new RegExp(`\\b${x.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\b`).test(text))}
function apply(){let a=state.recipes.filter(r=>{const q=state.query.trim().toLowerCase();const hay=(r.title+" "+r.category+" "+r.ingredients.join(" ")).toLowerCase();return(!q||hay.includes(q))&&(!state.category||r.category===state.category)&&(!state.maxIngredients||r.ingredients.length<=+state.maxIngredients)&&matchesDiet(r,state.diet)});if(state.sort==="az")a.sort((x,y)=>x.title.localeCompare(y.title));if(state.sort==="ingredients")a.sort((x,y)=>y.ingredients.length-x.ingredients.length);if(state.sort==="short")a.sort((x,y)=>x.ingredients.length-y.ingredients.length);state.filtered=a;state.visible=30;renderCatalog()}
function renderCatalog(){renderGrid($("#recipeGrid"),state.filtered.slice(0,state.visible));$("#resultMeta").textContent=`${state.filtered.length.toLocaleString()} recipes found`;$("#catalogTitle").textContent=state.query?`Results for “${escapeHtml(state.query)}”`:state.category?prettyCategory(state.category):"Popular recipes";$("#emptyState").classList.toggle("hidden",!!state.filtered.length);$("#loadMore").classList.toggle("hidden",state.visible>=state.filtered.length||!state.filtered.length)}
function renderCategories(){const counts={};state.recipes.forEach(r=>counts[r.category]=(counts[r.category]||0)+1);$("#categoryGrid").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<button class="category-card" data-cat="${escapeHtml(k)}"><div class="cat-icon">${icons[k]||"🍴"}</div><b>${escapeHtml(prettyCategory(k))}</b><small>${v.toLocaleString()} recipes</small></button>`).join("");$$(".category-card").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;$("#categorySelect").value=state.category;apply();location.hash="catalog"});$("#categorySelect").innerHTML='<option value="">All categories</option>'+Object.keys(counts).sort().map(k=>`<option value="${escapeHtml(k)}">${escapeHtml(prettyCategory(k))}</option>`).join("")}
function persist(){localStorage.setItem("feastly-saved",JSON.stringify([...state.saved]));$("#savedCount").textContent=state.saved.size}
function toggleSave(slug){state.saved.has(slug)?state.saved.delete(slug):state.saved.add(slug);persist();renderCatalog();renderSaved()}
function renderSaved(){const list=state.recipes.filter(r=>state.saved.has(r.slug));$("#savedMeta").textContent=`${list.length} saved recipe${list.length===1?"":"s"}.`;$("#savedEmpty").classList.toggle("hidden",!!list.length);renderGrid($("#savedGrid"),list.slice(0,12))}
function addShopping(ingredients){ingredients.forEach(x=>state.shopping[x]=true);saveShop();renderShopping()}
function saveShop(){localStorage.setItem("feastly-shopping",JSON.stringify(state.shopping))}
function renderShopping(){const items=Object.keys(state.shopping);$("#shoppingList").innerHTML=items.length?items.map(x=>`<label class="shop-item ${!state.shopping[x]?"done":""}"><input type="checkbox" ${state.shopping[x]?"":"checked"} data-shop="${encodeURIComponent(x)}"><span>${escapeHtml(x)}</span></label>`).join(""):`<div class="empty"><div>🛒</div><h3>Your list is empty</h3><p>Add ingredients from any recipe.</p></div>`;$$("[data-shop]").forEach(i=>i.onchange=()=>{state.shopping[decodeURIComponent(i.dataset.shop)]=!i.checked;saveShop();renderShopping()})}
function savePlanner(){localStorage.setItem("feastly-planner",JSON.stringify(state.planner))}
function renderPlanner(){["mon","tue","wed","thu","fri","sat","sun"].forEach(day=>{const el=document.querySelector(`[data-day="${day}"]`);if(!el)return;const r=state.recipes.find(x=>x.slug===state.planner[day]);el.innerHTML=state.planner[day]?`<button class="planned" data-planned="${encodeURIComponent(state.planner[day])}">${escapeHtml(r?.title||"Recipe")}</button>`:`<span class="drop-hint">Choose a recipe</span>`});$$("[data-planned]").forEach(b=>b.onclick=()=>openRecipe(decodeURIComponent(b.dataset.planned)))}
function openPlannerPicker(day){const q=prompt("Search your recipe collection for a recipe to add:");if(!q)return;const r=state.recipes.find(x=>x.title.toLowerCase().includes(q.toLowerCase()));if(r){state.planner[day]=r.slug;savePlanner();renderPlanner()}else alert("No matching recipe found in your local collection.")}
function startCook(r){state.cookSteps=r.directions||[];state.cookIndex=0;$("#cookTitle").textContent=r.title;$("#cookIngredients").innerHTML=r.ingredients.map(x=>`<li>${escapeHtml(x)}</li>`).join("");if(!state.cookSteps.length){$("#cookStep").textContent="This recipe's bundled source contains ingredients only. Open the original source for its cooking directions.";$("#cookSource").href=`https://www.allrecipes.com/recipe/${r.id}/`;$("#cookNext").disabled=true}else{$("#cookStep").textContent=state.cookSteps[0];$("#cookNext").disabled=false}$("#cookMode").classList.remove("hidden")}
function openRecipe(slug){const r=state.recipes.find(x=>x.slug===slug);if(!r)return;$("#modalCategory").textContent=prettyCategory(r.category);$("#modalTitle").textContent=r.title;$("#modalCount").textContent=`${r.ingredients.length} ingredients`;$("#modalType").textContent=r.directions?.length?`${r.directions.length} cooking steps`:"Ingredients dataset";$("#ingredientList").innerHTML=r.ingredients.map(x=>`<li>${escapeHtml(x)}</li>`).join("");$("#sourceLink").href=r.source||`https://www.allrecipes.com/recipe/${r.id}/`;$("#modalSave").textContent=state.saved.has(r.slug)?"♥ Saved":"♡ Save";$("#modalSave").onclick=()=>{toggleSave(r.slug);$("#modalSave").textContent=state.saved.has(r.slug)?"♥ Saved":"♡ Save"};$("#modalShop").onclick=()=>{addShopping(r.ingredients);$("#modalShop").textContent="✓ Added"};$("#modalCook").onclick=()=>startCook(r);$("#recipeModal").classList.remove("hidden");$("#modalImage").innerHTML=`<div class="image-fallback">${icons[r.category]||"🍴"}</div>`;findImage(r.title).then(src=>{if(src&&$("#recipeModal").classList.contains("hidden")===false)$("#modalImage").innerHTML=`<img alt="${escapeHtml(r.title)}" src="${src}">`})}
function showWebSearch(){const q=$("#webSearchInput").value.trim();if(!q)return;window.open(`https://www.google.com/search?q=${encodeURIComponent(q+" recipe")}`,"_blank","noopener");}
$("#searchInput").oninput=e=>{state.query=e.target.value;$("#clearSearch").classList.toggle("hidden",!state.query);apply()};$("#clearSearch").onclick=()=>{$("#searchInput").value="";state.query="";$("#clearSearch").classList.add("hidden");apply()};$$('[data-search]').forEach(b=>b.onclick=()=>{$("#searchInput").value=b.dataset.search;state.query=b.dataset.search;$("#clearSearch").classList.remove("hidden");apply();location.hash="catalog"});
$("#sortSelect").onchange=e=>{state.sort=e.target.value;apply()};$("#categorySelect").onchange=e=>{state.category=e.target.value;apply()};$("#ingredientSelect").onchange=e=>{state.maxIngredients=e.target.value;apply()};$("#dietSelect").onchange=e=>{state.diet=e.target.value;apply()};$("#filterBtn").onclick=()=>$("#filterPanel").classList.toggle("hidden");$("#resetFilters").onclick=()=>{$("#categorySelect").value="";$("#ingredientSelect").value="";$("#dietSelect").value="";state.category=state.maxIngredients=state.diet="";apply()};$("#loadMore").onclick=()=>{state.visible+=30;renderCatalog()};$("#showAllBtn").onclick=()=>{state.query="";$("#searchInput").value="";apply();location.hash="catalog"};$("#clearShopping").onclick=()=>{state.shopping={};saveShop();renderShopping()};
$$('[data-close]').forEach(x=>x.onclick=()=>x.closest('.modal').classList.add('hidden'));$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("feastly-dark",document.body.classList.contains("dark"))};if(localStorage.getItem("feastly-dark"))document.body.classList.add("dark");
$("#webSearchBtn").onclick=showWebSearch;$("#webSearchInput").onkeydown=e=>{if(e.key==="Enter")showWebSearch()};$("#cookClose").onclick=()=>$("#cookMode").classList.add("hidden");$("#cookNext").onclick=()=>{if(state.cookIndex<state.cookSteps.length-1){state.cookIndex++;$("#cookStep").textContent=state.cookSteps[state.cookIndex];$("#cookProgress").textContent=`Step ${state.cookIndex+1} of ${state.cookSteps.length}`}else{$("#cookStep").textContent="All steps complete — enjoy your meal!";$('#cookNext')?.setAttribute('disabled','disabled')}};
$$('[data-plan-day]').forEach(b=>b.onclick=()=>openPlannerPicker(b.dataset.planDay));
(async function init(){try{const r=await fetch("data/recipes.json");state.recipes=await r.json();renderCategories();apply();renderSaved();renderShopping();renderPlanner();persist();$("#statRecipes").textContent=state.recipes.length.toLocaleString()}catch(e){$("#resultMeta").textContent="Could not load recipe data. Run the app through a local web server."}})();
